### PR TITLE
Filter branches by author, align labels and badges

### PR DESCRIPTION
**Pull request by bcolmard-ebz**

### CODE REVIEW

**Comment by RonanDrouglazet** [comment]
Ho yeah very nice !! A big thank you for your contribution ! :)

**Comment by bcolmard-ebz** [comment]
I'm pleased to contribute and will do if I have more interesting ideas! 
As you see, I don't rely en bootstrap columns to align labels and badges, because I didn't want to break the elements ordering that is used to update rows.

**Comment by RonanDrouglazet** [comment]
okay !! I've pushed your modifications on ebz's GRebase (http://grebase.ebz.io), and i looooove your feature, simple and efficient !!

**Comment by bcolmard-ebz** [comment]
Cool! As you can see, there is a visual artifact when the author is empty (empty button), I didn't spend a lot of time on it, but it was safer to keep it if I didn't want to break the elements ordering used to update branches.

**Pull request merged**
